"""
Export the red-flag screen to the phone, so it works with no signal.

Writes `mobile/src/generated/emergencyRules.json`: every category, its reviewed
headline and action exactly as `emergency.py` holds them, its phrases, the
voided-prefix exception, and the concept combinations. Plus **parity cases** —
descriptions run through the real Python screen, with the category it
returned — so the phone's matcher is tested against this one rather than
against anybody's idea of it.

⛔ READ-ONLY WITH RESPECT TO THE FENCED MODULES. This imports `emergency.py`
and `symptom_concepts.py` and changes neither. There is one copy of the
phrase lists and one copy of the emergency copy, and they live there; this
file is a build step. `tests/test_emergency_export.py` fails when the JSON on
disk is stale, so a phrase added to `emergency.py` without re-running this is
a red suite, not a phone that silently screens with last month's list.

    cd backend
    python scripts/export_emergency_rules.py
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core import emergency, symptom_concepts  # noqa: E402

OUTPUT = ROOT.parent / "mobile" / "src" / "generated" / "emergencyRules.json"


def _load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# Edge cases the matcher has to get right, each one a bug this repository has
# had or a rule it states: plurals, the food-poisoning exception, glued lists,
# curly apostrophes, order-free combinations, and plain non-matches.
_EDGE_CASES = (
    "I am getting chest pains",
    "she had seizures",
    "I have had head injuries",
    "I have food poisoning, cramps and diarrhea",
    "I think this is poisoning",
    "Chest painShortness of breath",
    "I can’t breathe",
    "CHEST PAIN",
    "my neck is stiff and I have a fever",
    "a rash that does not fade and a stiff neck",
    "chest-pain",
    "chestpain",
    "a cold",
    "",
    "   ",
    "I stubbed my toe",
)


def parity_texts() -> list[str]:
    evals = ROOT / "scripts" / "triage_eval"
    corpus = _load("export_corpus", evals / "corpus.py")
    heldout = _load("export_heldout", evals / "heldout.py")
    texts: list[str] = list(_EDGE_CASES)
    for case in list(corpus.CASES) + heldout.TUNING + heldout.HELDOUT:
        texts.append(case.description)
    # Stable and de-duplicated, so the file only changes when the rules do.
    return list(dict.fromkeys(texts))


def build() -> dict:
    guidance_for = emergency.screen_for_emergency
    return {
        "_note": (
            "GENERATED by backend/scripts/export_emergency_rules.py from "
            "backend/app/core/emergency.py. Do not edit by hand."
        ),
        "rules": [
            {"category": c, "headline": h, "action": a, "phrases": list(p)}
            for c, h, a, p in emergency._EMERGENCY_RULES
        ],
        "voidedByPrefix": {k: list(v) for k, v in emergency._VOIDED_BY_PREFIX.items()},
        "concepts": {k: list(v) for k, v in symptom_concepts._CONCEPTS.items()},
        "combinations": [
            {"category": c.category, "required": list(c.required)}
            for c in symptom_concepts.combinations()
        ],
        "parity": [
            {"text": text, "category": (g.category if (g := guidance_for(text)) else None)}
            for text in parity_texts()
        ],
    }


def render() -> str:
    return json.dumps(build(), ensure_ascii=False, indent=1) + "\n"


# A larger parity set for the test suite only. It lives under __tests__ so it
# is never bundled into the app: every fourth description of the 11,272-case
# common-illness corpus, which carries the surface forms real text arrives in —
# curly apostrophes, block capitals, hurried spacing, pasted lists.
LARGE_FIXTURE = ROOT.parent / "mobile" / "__tests__" / "fixtures" / "emergencyParityLarge.json"


def render_large() -> str:
    sys.path.insert(0, str(ROOT / "scripts" / "triage_eval"))
    from common_illness import build_all  # noqa: E402

    texts = list(dict.fromkeys(case.description for case in build_all()))[::4]
    rows = [
        [text, g.category if (g := emergency.screen_for_emergency(text)) else None]
        for text in texts
    ]
    return json.dumps(rows, ensure_ascii=False) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    LARGE_FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    LARGE_FIXTURE.write_text(render_large(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT.parent)} and {LARGE_FIXTURE.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
